name: Distribute Grain
on:
  # A new Cred interval every Sunday. We'll distribute Grain 5 minutes
  # after the new interval
  schedule:
    - cron: 5 0 * * 0 # 00:05 UTC, 16:05 PST
  push:
    branches:
      # allows us to test this workflow, or manually generate distributions
      # PRSs created from grain-trigger-* branches are targeted
      # on their immediate base branches, as opposed to master
      - "grain-trigger-*"

jobs:
  distribute-grain:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Install Packages 🔧
        run: |
          yarn --frozen-lockfile

      - name: Load Data and Compute Cred 🧮
        run: yarn sourcecred go
        env:
          SOURCECRED_GITHUB_TOKEN: ${{ secrets.SOURCECRED_GITHUB_TOKEN }}
          SOURCECRED_DISCORD_TOKEN: ${{ secrets.SOURCECRED_DISCORD_TOKEN }}

      - name: Distribute Grain 💸
        run: yarn grain > grain_output.txt

      - name: Set environment variables
        id: pr_details
        run: |
          echo "PULL_REQUEST_TITLE=Distribución de BALLE programada para el final de la semana $(date +"%B %dth, %Y")" >> $GITHUB_ENV
          description="Este PR se generó el $(date +%d-%m-%Y) \
            para agregar la última distribución de BALLE a nuestra instancia.

            $(cat grain_output.txt)"
          description="${description//'%'/'%25'}"
          description="${description//$'\n'/'%0A'}"
          description="${description//$'\r'/'%0D'}"
          echo "::set-output name=pr_body::$description"
          rm grain_output.txt

      - name: Create commit and PR for ledger changes
        id: pr
        uses: peter-evans/create-pull-request@v4.1.3
        with:
          branch: generated-ledger
          branch-suffix: timestamp
          committer: cryptoballena <crypto@ballena.io>
          # author appears to be overridden when the default github action
          # token is used for checkout
          author: cryptoballena <crypto@ballena.io>
          commit-message: update calculated ledger
          title: ${{ env.PULL_REQUEST_TITLE }}
          body: ${{ steps.pr_details.outputs.pr_body }}
